import type { ComponentMeta } from "../../registry.types";

export const navigationPanelMeta = {
  category: "navigation",
  description: "A compound application navigation panel with independently addressable header, scroll body, content, grouped items, and footer anatomy.",
  maturity: "stable",
  name: "NavigationPanel",
  props: [
    { name: "children", type: "ReactNode" },
  ],
  states: ["default", "selected-item", "disabled-item", "scrolling"],
  tokens: [
    "color.surface.subtle",
    "color.border.subtle",
    "color.content.primary",
    "color.content.muted",
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.action.neutral.surface",
    "color.action.neutral.surfacePressed",
    "color.focus.ring",
    "type.label.selected.fontWeight",
    "layout.navigationPanel.inlineSize",
    "layout.navigationPanel.surfacePadding",
    "layout.navigationPanel.contentGap",
    "layout.navigationPanel.sectionGap",
    "layout.navigationPanel.headingHeight",
    "layout.navigationPanel.headingPaddingInline",
    "layout.navigationPanel.headingGap",
    "type.label.xs.fontSize",
    "layout.navigationPanel.headingActionSize",
    "layout.navigationPanel.itemHeight",
    "layout.navigationPanel.itemPaddingInline",
    "layout.navigationPanel.itemGap",
    "layout.navigationPanel.itemRadius",
    "layout.navigationPanel.itemIconSize",
    "layout.navigationPanel.scrollbarGap",
    "layout.navigationPanel.footerHeight",
    "layout.navigationPanel.footerPadding",
    "scrollbar.width",
    "scrollbar.radius",
  ],
} as const satisfies ComponentMeta;
