import type { ComponentMeta } from "../../registry.types";

export const toolbarMeta = {
  category: "navigation",
  description: "A responsive top-level bar with independent leading, centered, and trailing composition regions.",
  maturity: "stable",
  name: "Toolbar",
  props: [
    { name: "leading", type: "ReactNode" },
    { name: "center", type: "ReactNode" },
    { name: "trailing", type: "ReactNode" },
    { defaultValue: "sm", name: "size", type: "sm | md" },
    { defaultValue: "true", name: "bordered", type: "boolean" },
    { defaultValue: "visible", name: "leadingOverflow", type: "visible | scroll" },
  ],
  states: ["default", "with-center", "overflow"],
  tokens: [
    "color.surface.raised",
    "color.content.primary",
    "color.content.secondary",
    "color.border.subtle",
    "color.action.neutral.surface",
    "layout.toolbar.smHeight",
    "layout.toolbar.mdHeight",
    "layout.toolbar.contentGap",
    "layout.toolbar.smPaddingBlock",
    "layout.toolbar.smPaddingInline",
    "layout.toolbar.mdPaddingBlockStart",
    "layout.toolbar.mdPaddingBlockEnd",
    "layout.toolbar.mdPaddingInlineStart",
    "layout.toolbar.mdPaddingInlineEnd",
    "layout.toolbar.groupGapSm",
    "layout.toolbar.groupGapMd",
    "layout.toolbar.badgeSize",
    "type.meta.fontSize",
    "layout.toolbar.separatorBlockSize",
    "layout.toolbar.overflowFadeExtent",
    "radius.pill",
  ],
} as const satisfies ComponentMeta;
