import type { ComponentMeta } from "../../registry.types";

export const iconButtonMeta = {
  category: "action",
  description: "A labeled icon-only action with a transparent quiet variant and opaque filled and primary variants.",
  maturity: "stable",
  name: "IconButton",
  props: [
    { name: "aria-label", type: "string" },
    { name: "icon", type: "ReactNode" },
    { defaultValue: "quiet", name: "variant", type: "quiet | fill | primary" },
    { defaultValue: "square", name: "shape", type: "square | circle" },
    { defaultValue: "sm", name: "size", type: "xs | sm | md | lg" },
    { defaultValue: "neutral", name: "tone", type: "neutral | danger" },
    { defaultValue: "false", name: "loading", type: "boolean" },
  ],
  states: ["default", "hover", "active", "focus-visible", "disabled", "loading"],
  tokens: [
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.action.neutral.surface",
    "color.action.neutral.surfaceHover",
    "color.action.neutral.surfacePressed",
    "color.action.primary.background",
    "color.action.primary.content",
    "color.action.primary.hover",
    "color.action.primary.pressed",
    "color.surface.tertiary",
    "color.focus.ring",
    "color.status.danger.content",
    "color.status.danger.surface",
    "control.height.sm",
    "control.height.md",
    "control.height.lg",
    "control.iconButton.xsSize",
    "control.iconButton.xsIconSize",
    "radius.sm",
    "radius.pill",
  ],
} as const satisfies ComponentMeta;
