import type { ComponentMeta } from "../../registry.types";

export const searchFieldMeta = {
  category: "form",
  description: "A search input with optional leading icon, shortcut hint, clear action, Enter submission, and a frosted panel footer.",
  maturity: "stable",
  name: "SearchField",
  props: [
    { defaultValue: "default", name: "variant", type: "default | embedded | panel" },
    { name: "value", type: "string" },
    { name: "defaultValue", type: "string" },
    { name: "placeholder", type: "string" },
    { name: "leadingIcon", type: "ReactNode" },
    { name: "shortcut", type: "ReactNode" },
    { name: "trailing", type: "ReactNode" },
    { name: "footer", type: "ReactNode (panel only)" },
    { name: "clearLabel", type: "string" },
    { defaultValue: "sm", name: "size", type: "sm | md | lg" },
    { defaultValue: "false", name: "invalid", type: "boolean" },
    { defaultValue: "false", name: "disabled", type: "boolean" },
    { name: "onValueChange", type: "(value: string) => void" },
    { name: "onClear", type: "MouseEventHandler<HTMLButtonElement>" },
    { name: "onSearch", type: "(value: string) => void" },
  ],
  states: ["default", "hover", "focus-visible", "invalid", "disabled"],
  tokens: [
    "color.content.primary",
    "color.content.muted",
    "color.content.disabled",
    "color.surface.raised",
    "color.surface.subtle",
    "color.border.subtle",
    "color.field.background",
    "color.field.backgroundHover",
    "color.field.border",
    "color.field.borderHover",
    "color.field.borderFocus",
    "color.status.danger.border",
    "control.height.sm",
    "control.height.md",
    "control.height.lg",
    "type.label.md.fontSize",
    "type.meta.fontSize",
    "radius.pill",
    "radius.lg",
    "effect.blur.medium",
  ],
} as const satisfies ComponentMeta;
