import type { ComponentMeta } from "../../registry.types";

export const mobileListRowMeta = {
  category: "mobile",
  description: "A responsive touch row for mobile navigation and selection lists with semantic content slots.",
  maturity: "stable",
  name: "MobileListRow",
  props: [
    { name: "label", type: "ReactNode" },
    { name: "supportingText", type: "ReactNode" },
    { name: "leading", type: "ReactNode" },
    { name: "trailing", type: "ReactNode" },
    { defaultValue: "plain", name: "appearance", type: "plain | surface" },
    { defaultValue: "false", name: "selected", type: "boolean" },
    { defaultValue: "neutral", name: "tone", type: "neutral | danger" },
  ],
  states: ["default", "hover", "active", "focus-visible", "selected", "disabled"],
  tokens: [
    "color.action.neutral.surfaceHover",
    "color.action.neutral.surfacePressed",
    "color.border.strong",
    "color.border.subtle",
    "color.content.disabled",
    "color.content.muted",
    "color.content.primary",
    "color.content.secondary",
    "color.status.danger.content",
    "color.focus.ring",
    "color.surface.panel",
    "color.surface.tertiary",
    "radius.md",
    "shadow.xs",
    "space.1",
    "space.2",
    "space.3",
    "type.body.md.fontSize",
    "type.body.xs.fontSize",
    "type.label.lg.fontWeight",
  ],
} as const satisfies ComponentMeta;
