import type { ComponentMeta } from "../../registry.types";

export const activityItemMeta = {
  category: "feedback",
  description: "A compact activity row with independent identity, description, metadata, and sibling action areas.",
  maturity: "stable",
  name: "ActivityItem",
  props: [
    { name: "children", type: "ReactNode" },
    { name: "label", type: "ReactNode" },
    { name: "leading", type: "ReactNode" },
    { name: "metadata", type: "ReactNode" },
    { name: "detail", type: "ReactNode" },
    { defaultValue: "[]", name: "actions", type: "readonly ActivityItemAction[]" },
    { defaultValue: "inline", name: "appearance", type: "inline | surface" },
    { name: "onActivate", type: "MouseEventHandler<HTMLButtonElement>" },
    { defaultValue: "false", name: "disabled", type: "boolean" },
  ],
  states: ["default", "hover", "active", "focus-visible", "disabled"],
  tokens: [
    "color.surface.raised",
    "color.surface.subtle",
    "color.content.primary",
    "color.content.muted",
    "color.content.disabled",
    "color.border.subtle",
    "color.border.default",
    "color.action.neutral.surfacePressed",
    "color.codeChange.added",
    "color.codeChange.removed",
    "color.focus.ring",
    "control.activityItem.inlineGap",
    "control.activityItem.inlineIconSize",
    "type.meta.fontSize",
    "type.label.md.fontSize",
    "type.label.sm.fontWeight",
    "control.activityItem.surfaceHeight",
    "control.activityItem.surfaceGap",
    "control.activityItem.surfacePaddingBlock",
    "control.activityItem.surfacePaddingInlineStart",
    "control.activityItem.surfacePaddingInlineEnd",
    "control.activityItem.surfaceRadius",
    "control.activityItem.surfaceIconSize",
    "control.activityItem.contentGap",
    "control.activityItem.dividerBlockSize",
    "control.changeCount.gap",
    "control.changeCount.paddingBlock",
    "control.changeCount.paddingInline",
    "control.changeCount.radius",
    "control.iconButton.xsSize",
    "control.iconButton.xsIconSize",
  ],
} as const satisfies ComponentMeta;
