import type { ComponentMeta } from "../../registry.types";

export const chatComposerMeta = {
  category: "flow-chat",
  description: "A slot-based FlowChat composer with context, pending-message queue, and compact or expanded input anatomy.",
  maturity: "stable",
  name: "ChatComposer",
  props: [
    { defaultValue: "compact", name: "layout", type: "compact | expanded" },
    { name: "contextBar", type: "ReactNode" },
    { name: "queue", type: "ReactNode" },
    { name: "children", type: "ReactNode" },
    { name: "startActions", type: "ReactNode" },
    { name: "endActions", type: "ReactNode" },
    { defaultValue: "false", name: "busy", type: "boolean" },
    { defaultValue: "false", name: "disabled", type: "boolean" },
  ],
  states: ["default", "expanded", "queued", "focus-visible", "busy", "disabled"],
  tokens: [
    "border.width.default",
    "color.action.neutral.border",
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.action.neutral.surface",
    "color.action.neutral.surfaceHover",
    "color.action.neutral.surfacePressed",
    "color.action.primary.background",
    "color.action.primary.content",
    "color.action.primary.hover",
    "color.action.primary.pressed",
    "color.border.default",
    "color.content.muted",
    "color.content.primary",
    "color.content.secondary",
    "color.surface.panel",
    "color.surface.raised",
    "color.surface.subtle",
    "control.chatComposer.actionIconSize",
    "control.chatComposer.compactGap",
    "control.chatComposer.compactHeight",
    "control.chatComposer.compactPaddingBlock",
    "control.chatComposer.compactPaddingInline",
    "control.chatComposer.compactTrackHeight",
    "control.chatComposer.controlHeight",
    "control.height.md",
    "font.family.control",
    "font.size.base",
    "font.size.sm",
    "font.weight.medium",
    "font.weight.regular",
    "radius.lg",
    "radius.2xl",
    "radius.pill",
    "shadow.base",
    "space.1",
    "space.2",
    "space.3",
    "space.4",
    "space.6",
    "space.8",
    "space.12",
  ],
} as const satisfies ComponentMeta;
