import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const peerDeviceAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'peer-device',
  parts: [
    { id: 'overlay' },
    { id: 'dialog' },
    { id: 'header' },
    { id: 'title' },
    { id: 'closeButton' },
    { id: 'toolbar' },
    { id: 'toolButton' },
    { id: 'path' },
    { id: 'pathInput' },
    { id: 'pathDisplay' },
    { id: 'body' },
    { id: 'status' },
    { id: 'connectionStatus' },
    { id: 'connectionStatusContent' },
    { id: 'list' },
    { id: 'item' },
    { id: 'footer' },
    { id: 'selection' },
    { id: 'actions' },
    { id: 'switcher' },
    { id: 'switcherLabel' },
    { id: 'switcherElsewhere' },
    { id: 'switcherMenu' },
    { id: 'switcherItem' },
    { id: 'switcherStatusDot' },
  ],
  states: [
    { id: 'loading', selector: { kind: 'self', suffix: '[data-openbitfun-state~="loading"]' } },
    { id: 'error', selector: { kind: 'self', suffix: '[data-openbitfun-state~="error"]' } },
    { id: 'empty', selector: { kind: 'self', suffix: '[data-openbitfun-state~="empty"]' } },
    { id: 'selected', selector: { kind: 'self', suffix: '[data-openbitfun-state~="selected"]' } },
    { id: 'disabled', selector: { kind: 'self', suffix: ':disabled' } },
    { id: 'remote', selector: { kind: 'self', suffix: '[data-openbitfun-state~="remote"]' } },
    { id: 'local', selector: { kind: 'self', suffix: '[data-openbitfun-state~="local"]' } },
    { id: 'busy', selector: { kind: 'self', suffix: '[data-openbitfun-state~="busy"]' } },
    { id: 'offline', selector: { kind: 'self', suffix: '[data-openbitfun-state~="offline"]' } },
  ],
};
