import type { ComponentMeta } from "../../registry.types";

export const inputMeta = {
  category: "form",
  description: "A native text field with independent leading and trailing content slots.",
  maturity: "stable",
  name: "Input",
  props: [
    { name: "value", type: "string" },
    { name: "defaultValue", type: "string" },
    { name: "placeholder", type: "string" },
    { name: "leading", type: "ReactNode" },
    { name: "trailing", type: "ReactNode" },
    { defaultValue: "sm", name: "size", type: "sm | md | lg" },
    { defaultValue: "false", name: "invalid", type: "boolean" },
    { defaultValue: "false", name: "disabled", type: "boolean" },
    { name: "onValueChange", type: "(value: string) => void" },
  ],
  states: ["default", "hover", "focus-visible", "invalid", "disabled"],
  tokens: [
    "color.content.primary",
    "color.content.muted",
    "color.content.disabled",
    "color.field.background",
    "color.field.backgroundHover",
    "color.field.border",
    "color.field.borderHover",
    "color.field.borderFocus",
    "color.accent.default",
    "color.status.danger.border",
    "control.height.sm",
    "control.height.md",
    "control.height.lg",
    "type.label.md.fontSize",
    "radius.base",
  ],
} as const satisfies ComponentMeta;
