import type { ComponentMeta } from "../../registry.types";

export const fieldMeta = {
  category: "form",
  description: "Associates label content, optional actions, description, and adjacent controls with one primary form control.",
  maturity: "stable",
  name: "Field",
  props: [
    { name: "label", type: "ReactNode" },
    { name: "description", type: "ReactNode" },
    { name: "error", type: "ReactNode" },
    { name: "labelAction", type: "ReactNode" },
    { name: "controlLeading", type: "ReactNode" },
    { name: "controlTrailing", type: "ReactNode" },
    { defaultValue: "auto", name: "controlWidth", type: "auto | fill" },
    { defaultValue: "auto", name: "labelWidth", type: "auto | sm | md | lg" },
    { defaultValue: "md", name: "horizontalGap", type: "md | lg" },
    { defaultValue: "false", name: "required", type: "boolean" },
    { defaultValue: "vertical", name: "orientation", type: "horizontal | vertical" },
    { name: "children", type: "ReactElement" },
  ],
  states: ["default", "invalid"],
  tokens: [
    "color.content.requiredIndicator",
    "color.content.primary",
    "color.content.muted",
    "color.status.danger.content",
    "layout.field.rootGap",
    "layout.field.horizontalGap",
    "layout.field.horizontalGapWide",
    "layout.field.labelWidthSm",
    "layout.field.labelWidthMd",
    "layout.field.labelWidthLg",
    "layout.field.contentGap",
    "layout.field.labelGap",
    "layout.field.labelActionGap",
    "layout.field.controlGap",
    "type.label.md.fontSize",
    "type.support.fontSize",
  ],
} as const satisfies ComponentMeta;
