import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance/types';

export const todosSceneAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'todos',
  parts: [
    { id: 'root' },
    { id: 'header' },
    { id: 'headerActions' },
    { id: 'monthNavigation' },
    { id: 'panes' },
    { id: 'listPane' },
    { id: 'overview' },
    { id: 'rows' },
    { id: 'row' },
    { id: 'rowIcon' },
    { id: 'rowBody' },
    { id: 'rowBadge' },
    { id: 'rowError' },
    { id: 'rowActions' },
    { id: 'inactive' },
    { id: 'empty' },
    { id: 'calendarPane' },
    { id: 'calendar' },
    { id: 'calendarHead' },
    { id: 'calendarGrid' },
    { id: 'calendarCell' },
    { id: 'dayDetail' },
    { id: 'editor' },
    { id: 'editorIntro' },
    { id: 'editorBody' },
    { id: 'editorSection' },
    { id: 'editorGrid' },
    { id: 'editorRuntime' },
    { id: 'editorAdvanced' },
    { id: 'editorActions' },
    { id: 'field' },
    { id: 'warning' },
  ],
  states: [
    { id: 'selected', selector: { kind: 'self', suffix: '[data-openbitfun-state~="selected"]' } },
    { id: 'today', selector: { kind: 'self', suffix: '[data-openbitfun-state~="today"]' } },
    { id: 'outside', selector: { kind: 'self', suffix: '[data-openbitfun-state~="outside"]' } },
    { id: 'overdue', selector: { kind: 'self', suffix: '[data-openbitfun-state~="overdue"]' } },
    { id: 'disabled', selector: { kind: 'self', suffix: '[data-openbitfun-state~="disabled"]' } },
  ],
};
