#!/usr/bin/env node
/**
 * Package the built bridge as a DeepSeek Harness PROFILE, so an IDE launch is
 * `dsh --profile <name>` against the harness the user already installed.
 *
 * A profile is just a directory under `$DSH_HOME/profiles/`: a `package.json`
 * naming its bundle layers and a `cordis.patch.yml` holding entries. This
 * script writes one whose bundle list is EMPTY, which makes our composition the
 * whole tree — no in-box bundle contributes rows, so a mode like `minimal`
 * stays exactly as narrow as its preset says. The launcher rewrites a profile's
 * `cordis.yml` to an empty root on every boot, which is why the composition
 * ships as the patch layer instead.
 *
 * Nothing here installs a second copy of the harness. Every `@deepseek-ai/dsh-*`
 * row resolves from the user's own dsh through `$DSH_HOME/profiles/node_modules`,
 * the flat fallback the launcher maintains (one symlink per package in the
 * installation's dependency closure). Only the two packages OUTSIDE that
 * closure are vendored here.
 *
 * Usage: `node scripts/build-profile.mjs [--from-local] [--out <dir>]`
 * `--from-local` copies the vendored packages out of this package's own
 * node_modules (a linked harness checkout) instead of fetching the pinned
 * versions from the registry; use it offline, and expect a checkout's version
 * rather than the pinned one.
 */

import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { cpSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, dirname, join, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')

/** The profile directory OpenBitFun materializes this build into. */
export const PROFILE_NAME = 'openbitfun-acp'

/**
 * The oldest `@deepseek-ai/dsh` this build is known to boot against. The bridge
 * compiles against harness APIs; an older installation resolves the closure to
 * packages this code predates, and the failure would otherwise surface as a
 * module or service error with no hint about the cause.
 */
const MIN_DSH_VERSION = '0.1.0-rc.6'

/**
 * The only two runtime packages the harness installation does NOT already
 * expose: the ACP wire SDK (not a harness dependency at all) and the agent
 * spine, which ships as an examples package outside the `dsh` closure. Pinned,
 * because they must agree with the harness train named above.
 */
const VENDORED = {
  '@agentclientprotocol/sdk': '0.25.1',
  '@deepseek-ai/dsh-agent-spine-demo': '0.1.0-rc.6',
}

/** Basename of the build stamp OpenBitFun compares before re-materializing. */
const STAMP_FILENAME = '.openbitfun-bridge.json'

const { values } = parseArgs({
  args: process.argv.slice(2),
  options: { out: { type: 'string' }, 'from-local': { type: 'boolean' } },
  strict: true,
})

const OUT = resolve(PACKAGE_ROOT, values.out ?? 'dist-profile')

/**
 * Turn the leaf `cordis.yml` into a profile patch layer.
 *
 * The transform is textual on purpose: every comment in that file explains why
 * a row is where it is, and re-serializing through a YAML parser would drop all
 * of it. Indenting the whole document under one `- insert:` is exactly the
 * shape the in-box bundles use.
 * @param source - the contents of cordis.yml.
 * @returns the patch document.
 */
function toPatchLayer(source) {
  const body = source
    // The app row is loaded from source in development and from the emitted
    // tree here; the Loader resolves both against the profile directory.
    .replace(/^(\s*name:\s*)'\.\/src\/app\.ts'/m, "$1'./lib/app.js'")
    .split('\n')
    // Blank lines stay blank rather than becoming trailing whitespace.
    .map(line => line === '' ? '' : `    ${line}`)
    .join('\n')
  return `# GENERATED by scripts/build-profile.mjs from cordis.yml — do not edit.\n`
    + `#\n`
    + `# The profile's own patch layer, applied over an empty root: with no bundles\n`
    + `# in package.json, these rows ARE the tree.\n`
    + `- insert:\n${body}`
}

/**
 * Copy a directory into the output, skipping what never ships.
 * @param from - absolute source directory.
 * @param to - absolute destination directory.
 */
function copyTree(from, to) {
  cpSync(from, to, {
    recursive: true,
    dereference: true,
    filter: source => {
      // `basename`, not a hand-rolled slice on '/': a Windows path separates on
      // '\', where slicing on '/' yields the whole path and matches nothing.
      const base = basename(source)
      return base !== 'node_modules' && base !== '.git' && !base.endsWith('.map')
    },
  })
}

/**
 * Place one vendored package under the profile's own node_modules.
 *
 * Its transitive dependencies are NOT vendored: Node's parent walk continues
 * past the profile into `$DSH_HOME/profiles/node_modules`, where the harness
 * installation's closure already provides them.
 * @param name - the package name.
 * @param version - the pinned version, used when fetching from the registry.
 */
function vendor(name, version) {
  const destination = join(OUT, 'node_modules', name)
  mkdirSync(dirname(destination), { recursive: true })
  if (values['from-local'] === true) {
    copyTree(join(PACKAGE_ROOT, 'node_modules', name), destination)
    return
  }
  const staging = mkdtempSync(join(tmpdir(), 'dsh-acp-vendor-'))
  try {
    // Both commands run IN the staging directory so no argument ever carries an
    // absolute path. That is not tidiness: `npm` on Windows is a `.cmd` shim,
    // which Node refuses to spawn without a shell since CVE-2024-27980, and a
    // shell then re-splits every argument — an unquoted `C:\Users\...` path
    // would break on its first space. Keeping the arguments to bare package
    // names and one filename sidesteps quoting altogether, and also keeps a
    // drive letter away from `tar -f`, which GNU tar reads as a remote host.
    const packed = execFileSync(
      'npm',
      ['pack', `${name}@${version}`, '--silent'],
      { cwd: staging, encoding: 'utf8', shell: process.platform === 'win32' },
    )
      .split(/\r?\n/)
      .map(line => line.trim())
      .filter(line => line !== '')
      .at(-1)
    if (packed === undefined) {
      throw new Error(`npm pack ${name}@${version} named no tarball on stdout`)
    }
    execFileSync('tar', ['-xzf', packed], { cwd: staging })
    copyTree(join(staging, 'package'), destination)
  } finally {
    rmSync(staging, { recursive: true, force: true })
  }
}

/**
 * Hash every file in the output so OpenBitFun can tell one build from another.
 *
 * A version string is not enough: during development the bridge's version
 * stands still while its code changes, and a stale profile on disk would look
 * current. Paths are sorted so the digest does not depend on directory order,
 * and recorded with '/' so the same sources hash the same on every build host
 * rather than once per path separator.
 * @param root - the output directory, already fully written except the stamp.
 * @returns a hex digest over every path and its bytes.
 */
function hashTree(root) {
  const files = []
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name)
      if (entry.isDirectory()) walk(path)
      else files.push([relative(root, path).split(sep).join('/'), path])
    }
  }
  walk(root)
  const digest = createHash('sha256')
  for (const [key, path] of files.sort((a, b) => a[0] < b[0] ? -1 : 1)) {
    digest.update(key)
    digest.update('\0')
    digest.update(readFileSync(path))
  }
  return digest.digest('hex')
}

const manifest = JSON.parse(readFileSync(join(PACKAGE_ROOT, 'package.json'), 'utf8'))
try {
  statSync(join(PACKAGE_ROOT, 'lib', 'app.js'))
} catch {
  throw new Error('lib/app.js is missing; run `npm run build` (tsc -p tsconfig.build.json) first')
}

rmSync(OUT, { recursive: true, force: true })
mkdirSync(OUT, { recursive: true })

// A hand-written profile manifest is enough: the launcher only reads
// `dsh.profile.bundles` from it, and tolerates the section being absent. An
// empty list is deliberate — see the module comment.
writeFileSync(join(OUT, 'package.json'), `${JSON.stringify({
  name: `dsh-profile-${PROFILE_NAME}`,
  version: manifest.version,
  private: true,
  type: 'module',
  dependencies: {},
  dsh: { profile: { bundles: [] } },
}, undefined, 2)}\n`)

writeFileSync(
  join(OUT, 'cordis.patch.yml'),
  toPatchLayer(readFileSync(join(PACKAGE_ROOT, 'cordis.yml'), 'utf8')),
)

copyTree(join(PACKAGE_ROOT, 'lib'), join(OUT, 'lib'))
copyTree(join(PACKAGE_ROOT, 'presets'), join(OUT, 'presets'))
for (const [name, version] of Object.entries(VENDORED)) vendor(name, version)

writeFileSync(join(OUT, STAMP_FILENAME), `${JSON.stringify({
  bridge: manifest.version,
  content: hashTree(OUT),
  minDshVersion: MIN_DSH_VERSION,
  profile: PROFILE_NAME,
}, undefined, 2)}\n`)

process.stdout.write(`build-profile: wrote ${relative(PACKAGE_ROOT, OUT)} (profile ${PROFILE_NAME})\n`)
