import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const configAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'config',
  parts: [
    { id: 'root' },
    { id: 'content' },
    { id: 'contentInner' },
    { id: 'sectionStack' },
    { id: 'section' },
    { id: 'sectionHeader' },
    { id: 'sectionTitle' },
    { id: 'sectionDescription' },
    { id: 'sectionBody' },
    { id: 'row' },
    { id: 'rowLabel' },
    { id: 'required' },
    { id: 'rowDescription' },
    { id: 'rowControl' },
    { id: 'pageHeader' },
    { id: 'collectionSection' },
    { id: 'collectionItem' },
    { id: 'collectionRow' },
    { id: 'collectionMeta' },
    { id: 'collectionName' },
    { id: 'collectionControl' },
    { id: 'collectionDetails' },
    { id: 'collectionToolbar' },
    { id: 'collectionEditor' },
    { id: 'collectionFilters' },
    { id: 'collectionList' },
    { id: 'loadingState' },
    { id: 'emptyState' },
    { id: 'retryState' },
    { id: 'message' },
    { id: 'fieldStatus', propertyProfile: 'paint', visualRole: 'content' },
    { id: 'actionBar', propertyProfile: 'layout', visualRole: 'toolbar' },
    { id: 'pageHeaderInner' },
    { id: 'pageHeaderInfo' },
    { id: 'pageHeaderTitle' },
    { id: 'pageHeaderSubtitle' },
    { id: 'pageHeaderExtra' },
  ],
  facets: [
    { id: 'align', attribute: 'data-openbitfun-align', values: ['start', 'center'] },
    { id: 'layout', attribute: 'data-openbitfun-layout', values: ['default', 'multiline', 'wide', 'balanced'] },
    { id: 'status', attribute: 'data-openbitfun-status', values: ['unsaved', 'saving', 'saved', 'error'] },
  ],
};
