import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const flowChatHeaderAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'flow-chat-header',
  parts: [
    { id: 'root' },
    { id: 'leftActions' },
    { id: 'actions' },
    { id: 'sessionOverview' },
    { id: 'sessionOverviewTrigger' },
    { id: 'sessionOverviewPanel' },
    { id: 'sessionOverviewList' },
    { id: 'sessionOverviewItem' },
    { id: 'backgroundActivity' },
    { id: 'rightPanelTrigger' },
    { id: 'activitySection' },
    { id: 'commandMenu' },
    { id: 'commandItem' },
    { id: 'search' },
    { id: 'searchControls' },
    { id: 'sessionTree' },
    { id: 'sessionTreeTrigger' },
    { id: 'sessionTreePanel' },
    { id: 'sessionTreeHeader' },
    { id: 'sessionTreeBody' },
    { id: 'sessionTreeNode' },
    { id: 'sessionTreeNodeTitle' },
    { id: 'sessionTreeMenu' },
    { id: 'sessionTreeMenuItem' },
    { id: 'sessionTreeState' },
  ],
  facets: [
    {
      id: 'status',
      attribute: 'data-openbitfun-status',
      values: ['running', 'finishing', 'waiting', 'completed', 'cancelled', 'error', 'idle'],
    },
  ],
  states: [
    { id: 'open', selector: { kind: 'self', suffix: '[data-openbitfun-state~="open"]' } },
    { id: 'collapsed', selector: { kind: 'self', suffix: '[data-openbitfun-state~="collapsed"]' } },
    { id: 'active', selector: { kind: 'self', suffix: '[data-openbitfun-state~="active"]' } },
    { id: 'cancelling', selector: { kind: 'self', suffix: '[data-openbitfun-state~="cancelling"]' } },
    { id: 'loading', selector: { kind: 'self', suffix: '[data-openbitfun-state~="loading"]' } },
    { id: 'empty', selector: { kind: 'self', suffix: '[data-openbitfun-state~="empty"]' } },
    { id: 'unavailable', selector: { kind: 'self', suffix: '[data-openbitfun-state~="unavailable"]' } },
    { id: 'error', selector: { kind: 'self', suffix: '[data-openbitfun-state~="error"]' } },
  ],
};
