// Generated by scripts/mobile-ui-design-system.mjs. Do not edit.
import CoreGraphics

struct MobilePreviewMessage {
    let role: String
    let text: String
}

struct MobilePreviewScenario {
    let id: String
    let title: String
    let description: String
    let appearance: String
    let viewportWidth: CGFloat
    let viewportHeight: CGFloat
    let headerTitle: String
    let headerSubtitle: String
    let messages: [MobilePreviewMessage]
    let composerDraft: String
    let composerPlaceholder: String
    let connectionPhase: String
    let streaming: Bool
}

enum MobilePreviewScenarios {
    static let connectedConversation = MobilePreviewScenario(
        id: "connected-conversation",
        title: "Connected conversation",
        description: "A remote desktop is answering and the composer is ready.",
        appearance: "light",
        viewportWidth: 390,
        viewportHeight: 844,
        headerTitle: "统一移动端设计系统",
        headerSubtitle: "DESKTOP-KM3L4UI",
        messages: [MobilePreviewMessage(role: "user", text: "三端的组件和样式可以保持一致吗？"), MobilePreviewMessage(role: "assistant", text: "可以。共享视觉契约，三端继续使用原生渲染。")],
        composerDraft: "",
        composerPlaceholder: "向 OpenBitFun 提问",
        connectionPhase: "connected",
        streaming: false
    )

    static let streamingDark = MobilePreviewScenario(
        id: "streaming-dark",
        title: "Streaming in dark mode",
        description: "An active turn exercises dark surfaces and the stop action.",
        appearance: "dark",
        viewportWidth: 390,
        viewportHeight: 844,
        headerTitle: "跨端视觉校验",
        headerSubtitle: "正在由 MacBook Pro 运行",
        messages: [MobilePreviewMessage(role: "user", text: "比较三端的输入框、消息气泡和标题栏。"), MobilePreviewMessage(role: "assistant", text: "正在生成原生截图，并按相同基线并排展示。")],
        composerDraft: "检查深色模式下的边框对比度",
        composerPlaceholder: "输入消息",
        connectionPhase: "connected",
        streaming: true
    )

    static let reconnectingWide = MobilePreviewScenario(
        id: "reconnecting-wide",
        title: "Reconnecting on a wide viewport",
        description: "A tablet-sized viewport keeps remote blocking states answerable.",
        appearance: "light",
        viewportWidth: 1024,
        viewportHeight: 768,
        headerTitle: "远程会话",
        headerSubtitle: "正在恢复连接",
        messages: [MobilePreviewMessage(role: "assistant", text: "连接暂时中断。恢复后会从上次游标继续。")],
        composerDraft: "",
        composerPlaceholder: "等待重新连接",
        connectionPhase: "reconnecting",
        streaming: false
    )

    static let narrowMultiline = MobilePreviewScenario(
        id: "narrow-multiline",
        title: "Narrow phone with a multiline draft",
        description: "Narrow phone with a multiline draft",
        appearance: "light",
        viewportWidth: 360,
        viewportHeight: 800,
        headerTitle: "检查移动端长标题、正文与控制目标的可读性",
        headerSubtitle: "远程开发工作站 · OpenBitFun / feature/mobile-reading",
        messages: [MobilePreviewMessage(role: "user", text: "三端的组件和样式可以保持一致吗？"), MobilePreviewMessage(role: "assistant", text: "可以。共享视觉契约，三端继续使用原生渲染。")],
        composerDraft: "请检查输入框是否能保留多行中文草稿。\n模型选择后内容应继续保留。\n附件与文本应各自成行。",
        composerPlaceholder: "向 OpenBitFun 提问",
        connectionPhase: "connected",
        streaming: false
    )

    static let foldContext = MobilePreviewScenario(
        id: "fold-context",
        title: "Foldable with long remote context",
        description: "Foldable with long remote context",
        appearance: "light",
        viewportWidth: 700,
        viewportHeight: 840,
        headerTitle: "检查移动端长标题、正文与控制目标的可读性",
        headerSubtitle: "远程开发工作站 · OpenBitFun / feature/mobile-reading",
        messages: [MobilePreviewMessage(role: "user", text: "三端的组件和样式可以保持一致吗？"), MobilePreviewMessage(role: "assistant", text: "可以。共享视觉契约，三端继续使用原生渲染。")],
        composerDraft: "请保留当前会话与控制目标。",
        composerPlaceholder: "向 OpenBitFun 提问",
        connectionPhase: "connected",
        streaming: false
    )

    static let longReading = MobilePreviewScenario(
        id: "long-reading",
        title: "Long reading content",
        description: "Long reading content",
        appearance: "light",
        viewportWidth: 430,
        viewportHeight: 932,
        headerTitle: "检查移动端长标题、正文与控制目标的可读性",
        headerSubtitle: "远程开发工作站 · OpenBitFun / feature/mobile-reading",
        messages: [MobilePreviewMessage(role: "user", text: "三端的组件和样式可以保持一致吗？"), MobilePreviewMessage(role: "assistant", text: "移动端的阅读层级需要清晰，正文应该舒适地换行，辅助说明保留足够对比度。\n\n当内容变长时，消息区滚动，输入框仍然可以操作。请在系统大字体设置下检查这一场景。")],
        composerDraft: "",
        composerPlaceholder: "向 OpenBitFun 提问",
        connectionPhase: "connected",
        streaming: false
    )
}
