import type { ComponentMeta } from "../../registry.types";

export const tabGroupMeta = {
  category: "navigation",
  description: "A compact single-selection tab list with optional leading icons, end actions, and automatic keyboard activation.",
  maturity: "stable",
  name: "TabGroup",
  props: [
    { name: "items", type: "readonly TabGroupItem[]" },
    { name: "value", type: "string" },
    { name: "defaultValue", type: "string" },
    { name: "onValueChange", type: "(value: string) => void" },
    { defaultValue: "md", name: "size", type: "sm | md" },
  ],
  states: ["selected", "unselected", "hover", "disabled"],
  tokens: [
    "color.action.neutral.border",
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.action.neutral.surface",
    "color.action.neutral.surfaceHover",
    "color.action.neutral.surfacePressed",
    "color.content.primary",
    "color.focus.ring",
    "control.tabGroup.gap",
    "control.tabGroup.itemGap",
    "control.tabGroup.itemHeight",
    "control.tabGroup.itemHeightSm",
    "control.tabGroup.itemIconSize",
    "control.tabGroup.itemPaddingInline",
    "control.tabGroup.itemPaddingBlockSm",
    "control.tabGroup.itemPaddingInlineSm",
    "control.tabGroup.itemActionSize",
    "control.tabGroup.itemActionInset",
    "control.tabGroup.itemRadius",
    "type.label.md.fontSize",
    "type.label.md.lineHeight",
    "type.label.selected.fontWeight",
    "radius.pill",
  ],
} as const satisfies ComponentMeta;
