import type { ComponentMeta } from "../../registry.types";

export const composerMeta = {
  category: "form",
  description: "A composable message editor shell with independent context, editor, and action regions.",
  maturity: "stable",
  name: "Composer",
  props: [
    { name: "children", type: "ReactNode" },
    { name: "contextBar", type: "ReactNode" },
    { name: "toolbar", type: "ReactNode" },
    { defaultValue: "false", name: "invalid", type: "boolean" },
    { defaultValue: "false", name: "disabled", type: "boolean" },
  ],
  states: ["default", "focus-within", "with-context", "invalid", "disabled"],
  tokens: [
    "color.surface.raised",
    "color.surface.subtle",
    "color.border.subtle",
    "color.content.primary",
    "color.content.muted",
    "color.content.disabled",
    "color.field.border",
    "color.field.borderFocus",
    "color.focus.ring",
    "color.status.danger.border",
    "color.status.danger.surface",
    "control.composer.minBlockSize",
    "control.composer.contextOffset",
    "control.composer.contextPaddingBlock",
    "control.composer.contextPaddingInline",
    "control.composer.contextGap",
    "control.composer.surfacePadding",
    "control.composer.surfaceGap",
    "control.composer.surfaceRadius",
    "control.composer.editorPadding",
    "control.composer.toolbarGap",
    "control.composer.dividerBlockSize",
    "type.body.sm.fontSize",
    "shadow.composer",
  ],
} as const satisfies ComponentMeta;
