import type { ComponentMeta } from "../../registry.types";

export const askUserMeta = {
  category: "flow-chat",
  description: "A controlled, accessible question card with responsive options, custom answers, submission feedback, and an answered disclosure summary.",
  maturity: "stable",
  name: "AskUser",
  props: [
    { name: "questions", type: "readonly AskUserQuestion[]" },
    { defaultValue: "{}", name: "answers", type: "AskUserAnswers" },
    { defaultValue: "asking", name: "state", type: "AskUserState" },
    { name: "summaryLabel", type: "ReactNode" },
    { name: "summaryDetail", type: "ReactNode" },
    { defaultValue: "false", name: "expanded", type: "boolean" },
    { name: "onAnswersChange", type: "(questionId, values) => void" },
    { name: "onSubmit", type: "() => void" },
  ],
  states: [
    "asking",
    "selected",
    "submitting",
    "completed",
    "expanded",
    "loading",
    "error",
    "disabled",
  ],
  tokens: [
    "color.action.neutral.content",
    "color.action.neutral.surfaceHover",
    "color.border.default",
    "color.border.subtle",
    "color.content.disabled",
    "color.content.inverse",
    "color.content.muted",
    "color.content.primary",
    "color.content.secondary",
    "color.focus.ring",
    "color.status.danger.border",
    "color.status.danger.content",
    "color.status.danger.surface",
    "color.status.success.content",
    "color.status.warning.border",
    "color.status.warning.content",
    "color.status.warning.surface",
    "color.surface.panel",
    "color.surface.subtle",
    "control.askUser.bodyGap",
    "control.askUser.bodyPadding",
    "type.body.sm.lineHeight",
    "control.askUser.descriptionMaxWidth",
    "control.askUser.headerHeight",
    "control.askUser.iconSize",
    "control.askUser.optionContentGap",
    "control.askUser.optionGap",
    "control.askUser.optionPaddingBlock",
    "control.askUser.optionPaddingInline",
    "control.askUser.questionOptionsGap",
    "control.askUser.questionPaddingInline",
    "control.askUser.summaryActionSize",
    "control.askUser.summaryPaddingBlock",
    "control.askUser.summaryPaddingInlineEnd",
    "control.askUser.summaryPaddingInlineStart",
    "control.hitTarget",
    "font.family.control",
    "font.size.sm",
    "font.size.xs",
    "font.weight.medium",
    "font.weight.regular",
    "font.weight.semibold",
    "lineHeight.base",
    "lineHeight.tight",
    "radius.base",
    "radius.lg",
    "radius.xs",
  ],
} as const satisfies ComponentMeta;
